In [1]:
import pandas as pd
import keras
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np
from PIL import Image
import os

Using TensorFlow backend.


In [2]:
# Image.open('publish_dataset/train/positive/pos001.BMP').show()

In [3]:
# image_array_test = np.array(Image.open('publish_dataset/train/positive/pos001.BMP'))
# image_array_test

In [4]:
#image_array_test_flat= image_array_test.flatten()
#image_array_test_flat

In [5]:
df = pd.DataFrame([{'id':'1', 'label_car':1, 'label_car2':'car', 'array':0, 'vgg16_features':0}])

df

array id  label_car label_car2  vgg16_features
0      0  1          1        car               0

In [6]:
model = VGG16(weights='imagenet', include_top=False)

In [7]:
for filename in os.listdir('publish_dataset/train/positive'):
    image_array16 = np.array(Image.open(os.path.join('publish_dataset/train/positive/', filename)))
    img16 = image.load_img(os.path.join('publish_dataset/train/positive/', filename), target_size=(224, 224)) # resize to 224*224 
    x16 = image.img_to_array(img16)
    x16 = np.expand_dims(x16, axis=0)
    x16 = preprocess_input(x16)
    features16= model.predict(x16)
    features16=features16.flatten()
    print(filename)
    df = df.append(pd.DataFrame([{'id':filename, 'label_car':1, 'label_car2':'car','array':image_array16, 'vgg16_features':features16}]))

for filename in os.listdir('publish_dataset/train/negative'):
    image_array16 = np.array(Image.open(os.path.join('publish_dataset/train/negative/', filename)))
    img16 = image.load_img(os.path.join('publish_dataset/train/negative/', filename), target_size=(224, 224)) # resize to 224*224 
    x16 = image.img_to_array(img16)
    x16 = np.expand_dims(x16, axis=0)
    x16 = preprocess_input(x16)
    features16= model.predict(x16)
    features16=features16.flatten()
    print(filename)
    df = df.append(pd.DataFrame([{'id':filename, 'label_car':0, 'label_car2':'no','array':image_array16, 'vgg16_features':features16}]))  

df.head()

pos171.BMP
pos055.BMP
pos187.BMP
pos359.BMP
pos260.BMP
pos369.BMP
pos046.BMP
pos394.BMP
pos280.BMP
pos126.BMP
pos447.BMP
pos395.BMP
pos252.BMP
pos211.BMP
pos160.BMP
pos410.BMP
pos313.BMP
pos072.BMP
pos330.BMP
pos156.BMP
pos377.BMP
pos075.BMP
pos004.BMP
pos303.BMP
pos177.BMP
pos248.BMP
pos120.BMP
pos284.BMP
pos373.BMP
pos425.BMP
pos233.BMP
pos166.BMP
pos083.BMP
pos131.BMP
pos390.BMP
pos053.BMP
pos040.BMP
pos299.BMP
pos277.BMP
pos265.BMP
pos259.BMP
pos412.BMP
pos419.BMP
pos041.BMP
pos069.BMP
pos320.BMP
pos057.BMP
pos257.BMP
pos065.BMP
pos411.BMP
pos164.BMP
pos169.BMP
pos016.BMP
pos212.BMP
pos020.BMP
pos241.BMP
pos102.BMP
pos243.BMP
pos249.BMP
pos269.BMP
pos121.BMP
pos185.BMP
pos153.BMP
pos358.BMP
pos106.BMP
pos325.BMP
pos162.BMP
pos421.BMP
pos138.BMP
pos300.BMP
pos328.BMP
pos035.BMP
pos207.BMP
pos340.BMP
pos084.BMP
pos061.BMP
pos278.BMP
pos158.BMP
pos367.BMP
pos190.BMP
pos012.BMP
pos378.BMP
pos034.BMP
pos184.BMP
pos174.BMP
pos188.BMP
pos240.BMP
pos442.BMP
pos201.BMP
pos068.BMP
pos060.BMP

neg182.bmp
neg104.bmp
neg082.bmp
neg343.bmp
neg068.bmp
neg250.bmp
neg214.bmp
neg397.bmp
neg036.bmp
neg044.bmp
neg048.bmp
neg351.bmp
neg402.bmp
neg237.bmp
neg041.bmp
neg408.bmp
neg380.bmp
neg004.bmp
neg175.bmp
neg066.bmp
neg201.bmp
neg367.bmp
neg347.bmp
neg173.bmp
neg273.bmp
neg251.bmp
neg167.bmp
neg234.bmp
neg023.bmp
neg151.bmp
neg259.bmp
neg340.bmp
neg328.bmp
neg421.bmp
neg405.bmp
neg192.bmp
neg413.bmp
neg238.bmp
neg372.bmp
neg444.bmp
neg416.bmp
neg261.bmp
neg202.bmp
neg193.bmp
neg379.bmp
neg109.bmp
neg110.bmp
neg101.bmp
neg446.bmp
neg053.bmp
neg196.bmp
neg317.bmp
neg217.bmp
neg030.bmp
neg099.bmp
neg139.bmp
neg279.bmp
neg034.bmp
neg387.bmp
neg252.bmp
neg424.bmp
neg122.bmp
neg312.bmp
neg323.bmp
neg271.bmp
neg076.bmp
neg283.bmp
neg449.bmp
neg411.bmp
neg031.bmp
neg447.bmp
neg423.bmp
neg440.bmp
neg431.bmp
neg045.bmp
neg057.bmp
neg427.bmp
neg434.bmp
neg170.bmp
neg394.bmp
neg314.bmp
neg419.bmp
neg443.bmp
neg171.bmp
neg225.bmp
neg144.bmp
neg215.bmp
neg337.bmp
neg400.bmp
neg254.bmp
neg185.bmp

array          id  label_car  \
0                                                  0           1          1   
0  [[[62, 44, 28], [59, 40, 24], [61, 40, 25], [6...  pos171.BMP          1   
0  [[[57, 67, 75], [57, 67, 73], [57, 67, 72], [6...  pos055.BMP          1   
0  [[[14, 4, 6], [14, 4, 4], [13, 3, 3], [8, 2, 1...  pos187.BMP          1   
0  [[[33, 11, 5], [33, 13, 1], [22, 7, 3], [20, 9...  pos359.BMP          1   

  label_car2                                     vgg16_features  
0        car                                                  0  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [8]:
df.head(20)

array          id  label_car  \
0                                                  0           1          1   
0  [[[62, 44, 28], [59, 40, 24], [61, 40, 25], [6...  pos171.BMP          1   
0  [[[57, 67, 75], [57, 67, 73], [57, 67, 72], [6...  pos055.BMP          1   
0  [[[14, 4, 6], [14, 4, 4], [13, 3, 3], [8, 2, 1...  pos187.BMP          1   
0  [[[33, 11, 5], [33, 13, 1], [22, 7, 3], [20, 9...  pos359.BMP          1   
0  [[[7, 0, 0], [8, 1, 0], [8, 2, 0], [8, 2, 0], ...  pos260.BMP          1   
0  [[[55, 54, 48], [56, 54, 49], [57, 53, 50], [5...  pos369.BMP          1   
0  [[[93, 96, 94], [91, 88, 84], [184, 181, 178],...  pos046.BMP          1   
0  [[[57, 51, 53], [56, 51, 53], [62, 55, 55], [5...  pos394.BMP          1   
0  [[[25, 15, 4], [25, 15, 4], [25, 15, 3], [26, ...  pos280.BMP          1   
0  [[[31, 8, 6], [32, 8, 7], [32, 8, 8], [35, 8, ...  pos126.BMP          1   
0  [[[75, 75, 75], [76, 77, 80], [75, 76, 79], [7...  pos447.BMP          1   
0  [[[64, 47, 45], [65, 46, 45], [64, 46, 45], [6...  pos395.BMP          1   
0  [[[63, 59, 47], [93, 90, 77], [123, 121, 111],...  pos252.BMP          1   
0  [[[9, 4, 0], [8, 3, 0], [8, 2, 0], [9, 1, 0], ...  pos211.BMP          1   
0  [[[8, 0, 0], [7, 0, 0], [9, 0, 0], [11, 0, 0],...  pos160.BMP          1   
0  [[[64, 66, 66], [66, 69, 68], [66, 71, 70], [6...  pos410.BMP          1   
0  [[[21, 21, 7], [28, 25, 11], [31, 24, 9], [38,...  pos313.BMP          1   
0  [[[8, 5, 9], [7, 4, 8], [5, 2, 6], [6, 3, 7], ...  pos072.BMP          1   
0  [[[46, 44, 45], [48, 44, 46], [48, 43, 45], [4...  pos330.BMP          1   

  label_car2                                     vgg16_features  
0        car                                                  0  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 1.46477, 0.0, 0.0, 0.0, 0.0, 0...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 5.85657, 1.4975...  
0        car  [0.0, 0.0, 0.0, 0.0594719, 0.0, 0.0, 0.0, 0.0,...  
0        car  [0.0, 0.0, 0.0, 0.0, 3.44408, 0.0, 0.0, 0.0, 0...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 15.6003, 0.0, 0.0, 0.0, 0.0, 0...  
0        car  [0.0, 0.0, 0.0, 0.480065, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 4.32626, 0.0, 0.0, 1.62867, 0....  
0        car  [0.0, 0.0, 0.0, 0.0, 3.07767, 0.0, 0.0, 0.0, 0...

In [9]:
df.tail(20)

array          id  label_car  \
0  [[[25, 11, 0], [24, 10, 2], [22, 8, 0], [21, 7...  neg352.bmp          0   
0  [[[5, 7, 4], [7, 6, 1], [8, 7, 0], [9, 10, 0],...  neg276.bmp          0   
0  [[[42, 81, 106], [34, 72, 96], [35, 71, 97], [...  neg292.bmp          0   
0  [[[59, 68, 67], [61, 68, 64], [54, 60, 56], [5...  neg284.bmp          0   
0  [[[135, 30, 18], [125, 19, 9], [132, 14, 8], [...  neg131.bmp          0   
0  [[[20, 21, 7], [22, 23, 12], [24, 25, 12], [26...  neg338.bmp          0   
0  [[[84, 110, 100], [77, 103, 89], [55, 79, 67],...  neg075.bmp          0   
0  [[[50, 55, 40], [56, 62, 46], [57, 63, 48], [5...  neg374.bmp          0   
0  [[[73, 74, 83], [73, 73, 81], [83, 82, 91], [8...  neg223.bmp          0   
0  [[[0, 0, 2], [0, 0, 2], [0, 0, 3], [0, 0, 2], ...  neg334.bmp          0   
0  [[[29, 26, 14], [28, 26, 18], [30, 28, 20], [3...  neg344.bmp          0   
0  [[[33, 24, 25], [33, 24, 25], [33, 24, 24], [3...  neg195.bmp          0   
0  [[[26, 27, 21], [25, 25, 23], [24, 24, 19], [2...  neg062.bmp          0   
0  [[[27, 19, 9], [27, 19, 9], [28, 20, 11], [28,...  neg303.bmp          0   
0  [[[13, 1, 0], [15, 4, 0], [19, 7, 0], [20, 7, ...  neg425.bmp          0   
0  [[[30, 24, 18], [32, 24, 20], [47, 16, 9], [68...  neg072.bmp          0   
0  [[[17, 15, 12], [22, 17, 15], [18, 17, 9], [18...  neg241.bmp          0   
0  [[[4, 8, 6], [4, 8, 5], [2, 7, 3], [4, 8, 7], ...  neg095.bmp          0   
0  [[[48, 84, 127], [49, 85, 128], [50, 85, 128],...  neg282.bmp          0   
0  [[[40, 19, 15], [39, 19, 10], [39, 19, 12], [3...  neg078.bmp          0   

  label_car2                                     vgg16_features  
0         no  [0.0, 0.0, 0.0, 7.60373, 0.0, 0.0, 0.0, 0.0, 0...  
0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0         no  [0.0, 0.0, 0.0, 0.0, 31.5915, 0.0, 0.0, 0.0, 0...  
0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.35138, 0.0, 0...  
0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0         no  [0.0, 0.0, 0.0, 5.1849, 0.0, 0.0, 0.0, 0.0, 0....  
0         no  [0.0, 0.0, 0.0, 0.411457, 0.0, 0.0, 0.0, 0.0, ...  
0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0         no  [0.0, 0.0, 0.0, 10.2517, 0.0, 0.0, 0.0, 0.0, 0...  
0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0         no  [0.0, 14.0991, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2...  
0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0         no  [0.0, 0.0, 0.0, 2.3975, 0.0, 0.0, 0.0, 0.0, 0....  
0         no  [0.0, 0.0, 0.0, 11.0439, 0.0, 0.0, 3.77392, 0....  
0         no  [0.0, 0.0, 0.0, 0.0, 0.111555, 0.0, 0.0, 0.0, ...  
0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [10]:
df=df[df['id'] != '1']  #remove first row
df.head()

array          id  label_car  \
0  [[[62, 44, 28], [59, 40, 24], [61, 40, 25], [6...  pos171.BMP          1   
0  [[[57, 67, 75], [57, 67, 73], [57, 67, 72], [6...  pos055.BMP          1   
0  [[[14, 4, 6], [14, 4, 4], [13, 3, 3], [8, 2, 1...  pos187.BMP          1   
0  [[[33, 11, 5], [33, 13, 1], [22, 7, 3], [20, 9...  pos359.BMP          1   
0  [[[7, 0, 0], [8, 1, 0], [8, 2, 0], [8, 2, 0], ...  pos260.BMP          1   

  label_car2                                     vgg16_features  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0        car  [0.0, 0.0, 0.0, 1.46477, 0.0, 0.0, 0.0, 0.0, 0...

In [11]:
df.to_json('car.or.not.train.json', orient='records')

In [12]:
df2 = pd.DataFrame([{'id':'1', 'label_car':1, 'label_car2':'car', 'array':0, 'vgg16_features':0}])

df2

array id  label_car label_car2  vgg16_features
0      0  1          1        car               0

In [13]:
for filename in os.listdir('publish_dataset/train/test/positive'):
    image_array16 = np.array(Image.open(os.path.join('publish_dataset/train/test/positive/', filename)))
    img16 = image.load_img(os.path.join('publish_dataset/train/test/positive/', filename), target_size=(224, 224)) # resize to 224*224 
    x16 = image.img_to_array(img16)
    x16 = np.expand_dims(x16, axis=0)
    x16 = preprocess_input(x16)
    features16= model.predict(x16)
    features16=features16.flatten()
    print(filename)
    df2 = df2.append(pd.DataFrame([{'id':filename, 'label_car':1, 'label_car2':'car', 'array':image_array16, 'vgg16_features':features16}]))

for filename in os.listdir('publish_dataset/train/test/negative'):
    image_array16 = np.array(Image.open(os.path.join('publish_dataset/train/test/negative/', filename)))
    img16 = image.load_img(os.path.join('publish_dataset/train/test/negative/', filename), target_size=(224, 224)) # resize to 224*224 
    x16 = image.img_to_array(img16)
    x16 = np.expand_dims(x16, axis=0)
    x16 = preprocess_input(x16)
    features16= model.predict(x16)
    features16=features16.flatten()
    print(filename)
    df2 = df2.append(pd.DataFrame([{'id':filename, 'label_car':0, 'label_car2':'no', 'array':image_array16, 'vgg16_features':features16}]))  



testpos0101.BMP
testpos0365.BMP
testpos0218.BMP
testpos0334.BMP
testpos0319.BMP
testpos0220.BMP
testpos0129.BMP
testpos0041.BMP
testpos0423.BMP
testpos0316.BMP
testpos0053.BMP
testpos0376.BMP
testpos0255.BMP
testpos0393.BMP
testpos0008.BMP
testpos0340.BMP
testpos0222.BMP
testpos0025.BMP
testpos0328.BMP
testpos0320.BMP
testpos0410.BMP
testpos0043.BMP
testpos0417.BMP
testpos0231.BMP
testpos0049.BMP
testpos0235.BMP
testpos0275.BMP
testpos0442.BMP
testpos0446.BMP
testpos0269.BMP
testpos0181.BMP
testpos0003.BMP
testpos0161.BMP
testpos0204.BMP
testpos0005.BMP
testpos0128.BMP
testpos0169.BMP
testpos0357.BMP
testpos0307.BMP
testpos0233.BMP
testpos0349.BMP
testpos0113.BMP
testpos0371.BMP
testpos0306.BMP
testpos0398.BMP
testpos0015.BMP
testpos0265.BMP
testpos0186.BMP
testpos0196.BMP
testpos0102.BMP
testpos0386.BMP
testpos0059.BMP
testpos0032.BMP
testpos0422.BMP
testpos0061.BMP
testpos0359.BMP
testpos0230.BMP
testpos0384.BMP
testpos0250.BMP
testpos0048.BMP
testpos0434.BMP
testpos0125.BMP
testpos0

testneg078.bmp
testneg046.bmp
testneg327.bmp
testneg284.bmp
testneg094.bmp
testneg413.bmp
testneg362.bmp
testneg220.bmp
testneg076.bmp
testneg237.bmp
testneg140.bmp
testneg273.bmp
testneg330.bmp
testneg449.bmp
testneg248.bmp
testneg119.bmp
testneg226.bmp
testneg365.bmp
testneg085.bmp
testneg305.bmp
testneg325.bmp
testneg275.bmp
testneg168.bmp
testneg433.bmp
testneg045.bmp
testneg285.bmp
testneg333.bmp
testneg280.bmp
testneg099.bmp
testneg315.bmp
testneg256.bmp
testneg036.bmp
testneg215.bmp
testneg058.bmp
testneg251.bmp
testneg317.bmp
testneg176.bmp
testneg034.bmp
testneg442.bmp
testneg100.bmp
testneg142.bmp
testneg201.bmp
testneg177.bmp
testneg200.bmp
testneg347.bmp
testneg192.bmp
testneg093.bmp
testneg411.bmp
testneg276.bmp
testneg123.bmp
testneg291.bmp
testneg149.bmp
testneg214.bmp
testneg376.bmp
testneg259.bmp
testneg202.bmp
testneg446.bmp
testneg083.bmp
testneg128.bmp
testneg434.bmp
testneg049.bmp
testneg351.bmp
testneg169.bmp
testneg309.bmp
testneg018.bmp
testneg383.bmp
testneg342

array               id  \
0                                                  0                1   
0  [[[20, 16, 5], [20, 16, 3], [19, 16, 2], [16, ...  testpos0101.BMP   
0  [[[30, 25, 21], [29, 24, 20], [28, 24, 20], [2...  testpos0365.BMP   
0  [[[11, 6, 1], [10, 5, 0], [8, 5, 0], [10, 7, 0...  testpos0218.BMP   
0  [[[61, 78, 88], [99, 116, 129], [102, 127, 140...  testpos0334.BMP   

   label_car label_car2                                     vgg16_features  
0          1        car                                                  0  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          1        car  [0.0, 0.0, 0.0, 5.62062, 6.42057, 0.0, 0.0, 0....  
0          1        car  [0.0, 0.0, 0.0, 5.28827, 0.0, 0.0, 0.0, 0.0, 0...  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.236765, 0.0, ...

In [16]:
df2.head(20)

array               id  \
0  [[[20, 16, 5], [20, 16, 3], [19, 16, 2], [16, ...  testpos0101.BMP   
0  [[[30, 25, 21], [29, 24, 20], [28, 24, 20], [2...  testpos0365.BMP   
0  [[[11, 6, 1], [10, 5, 0], [8, 5, 0], [10, 7, 0...  testpos0218.BMP   
0  [[[61, 78, 88], [99, 116, 129], [102, 127, 140...  testpos0334.BMP   
0  [[[34, 23, 13], [31, 21, 11], [31, 21, 13], [3...  testpos0319.BMP   
0  [[[9, 7, 0], [12, 7, 0], [12, 7, 0], [13, 7, 0...  testpos0220.BMP   
0  [[[8, 0, 8], [4, 0, 3], [4, 0, 0], [4, 0, 0], ...  testpos0129.BMP   
0  [[[5, 0, 0], [6, 0, 0], [6, 0, 0], [6, 0, 0], ...  testpos0041.BMP   
0  [[[4, 7, 8], [5, 6, 6], [2, 2, 2], [1, 1, 0], ...  testpos0423.BMP   
0  [[[16, 3, 1], [15, 2, 0], [14, 2, 0], [17, 4, ...  testpos0316.BMP   
0  [[[9, 0, 0], [11, 1, 0], [12, 2, 0], [10, 2, 0...  testpos0053.BMP   
0  [[[13, 1, 0], [16, 2, 0], [19, 3, 0], [21, 4, ...  testpos0376.BMP   
0  [[[14, 5, 0], [14, 5, 0], [15, 6, 0], [15, 7, ...  testpos0255.BMP   
0  [[[9, 0, 0], [10, 0, 0], [17, 1, 0], [20, 2, 0...  testpos0393.BMP   
0  [[[15, 9, 14], [15, 9, 14], [15, 9, 14], [15, ...  testpos0008.BMP   
0  [[[199, 193, 188], [191, 180, 175], [193, 178,...  testpos0340.BMP   
0  [[[14, 9, 0], [16, 9, 0], [17, 7, 3], [19, 8, ...  testpos0222.BMP   
0  [[[18, 14, 8], [18, 14, 8], [18, 14, 8], [18, ...  testpos0025.BMP   
0  [[[0, 0, 0], [1, 0, 0], [0, 0, 0], [0, 0, 0], ...  testpos0328.BMP   
0  [[[12, 7, 4], [11, 9, 12], [11, 11, 12], [11, ...  testpos0320.BMP   

   label_car label_car2                                     vgg16_features  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          1        car  [0.0, 0.0, 0.0, 5.62062, 6.42057, 0.0, 0.0, 0....  
0          1        car  [0.0, 0.0, 0.0, 5.28827, 0.0, 0.0, 0.0, 0.0, 0...  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.236765, 0.0, ...  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          1        car  [0.0, 0.0, 0.0, 0.0877071, 0.0, 0.0, 0.0, 0.0,...  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          1        car  [0.0, 0.0, 0.0, 1.50124, 0.0, 0.0, 0.0, 0.0, 0...  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.64594, 0.0, 0...  
0          1        car  [0.0, 0.0, 0.0, 7.32755, 0.0, 0.0, 0.0, 0.0, 0...  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          1        car  [0.0, 0.0, 0.0, 1.28955, 0.0, 0.0, 0.0, 0.0, 0...  
0          1        car  [0.0, 0.0, 0.0, 0.0, 2.27092, 0.0, 0.0, 0.0, 0...  
0          1        car  [0.0, 0.0, 0.0, 1.68995, 0.0, 0.0, 0.0, 0.0, 0...

In [17]:
df2.tail(20)

array              id  \
0  [[[14, 10, 5], [12, 8, 1], [12, 6, 2], [11, 5,...  testneg206.bmp   
0  [[[20, 17, 17], [20, 17, 17], [21, 19, 15], [2...  testneg378.bmp   
0  [[[1, 1, 9], [4, 3, 10], [3, 2, 7], [3, 2, 6],...  testneg228.bmp   
0  [[[22, 20, 15], [23, 21, 14], [22, 20, 15], [2...  testneg079.bmp   
0  [[[17, 17, 15], [16, 17, 16], [17, 19, 19], [4...  testneg174.bmp   
0  [[[33, 24, 24], [33, 24, 20], [33, 24, 20], [3...  testneg156.bmp   
0  [[[81, 93, 103], [73, 84, 94], [55, 68, 79], [...  testneg250.bmp   
0  [[[8, 4, 2], [12, 6, 3], [11, 6, 6], [13, 6, 3...  testneg334.bmp   
0  [[[60, 73, 63], [57, 69, 60], [45, 58, 49], [4...  testneg391.bmp   
0  [[[9, 0, 0], [4, 0, 0], [4, 0, 0], [7, 2, 1], ...  testneg166.bmp   
0  [[[32, 37, 29], [37, 40, 32], [36, 40, 34], [3...  testneg056.bmp   
0  [[[15, 22, 19], [14, 20, 20], [13, 20, 21], [1...  testneg086.bmp   
0  [[[5, 8, 8], [5, 8, 5], [5, 8, 5], [5, 8, 6], ...  testneg005.bmp   
0  [[[14, 10, 2], [14, 10, 3], [13, 10, 3], [13, ...  testneg028.bmp   
0  [[[8, 4, 4], [7, 3, 3], [7, 3, 3], [7, 3, 3], ...  testneg345.bmp   
0  [[[17, 13, 2], [15, 13, 7], [12, 10, 3], [11, ...  testneg443.bmp   
0  [[[14, 7, 4], [15, 5, 3], [13, 4, 2], [12, 3, ...  testneg057.bmp   
0  [[[43, 13, 0], [44, 14, 0], [43, 13, 0], [41, ...  testneg071.bmp   
0  [[[64, 40, 28], [64, 40, 29], [60, 39, 25], [6...  testneg353.bmp   
0  [[[41, 77, 106], [43, 78, 108], [44, 79, 111],...  testneg240.bmp   

   label_car label_car2                                     vgg16_features  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.21674, 0.0, 0...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 16.4764, 0.0, 0...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 0.138937, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 2.35889, 0.0, 0.0, 0.0, 0.0, 0...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          0         no  [0.0, 0.0, 0.0, 0.0, 8.10873, 0.0, 0.0, 0.0, 0...

In [15]:
df2=df2[df2['id'] != '1']  #remove first row
df2.head()

array               id  \
0  [[[20, 16, 5], [20, 16, 3], [19, 16, 2], [16, ...  testpos0101.BMP   
0  [[[30, 25, 21], [29, 24, 20], [28, 24, 20], [2...  testpos0365.BMP   
0  [[[11, 6, 1], [10, 5, 0], [8, 5, 0], [10, 7, 0...  testpos0218.BMP   
0  [[[61, 78, 88], [99, 116, 129], [102, 127, 140...  testpos0334.BMP   
0  [[[34, 23, 13], [31, 21, 11], [31, 21, 13], [3...  testpos0319.BMP   

   label_car label_car2                                     vgg16_features  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
0          1        car  [0.0, 0.0, 0.0, 5.62062, 6.42057, 0.0, 0.0, 0....  
0          1        car  [0.0, 0.0, 0.0, 5.28827, 0.0, 0.0, 0.0, 0.0, 0...  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.236765, 0.0, ...  
0          1        car  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [18]:
df2.to_json('car.or.not.test.json', orient='records')

In [46]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [37]:
array_features = np.asarray(df['vgg16_features'])
array_features

array([ array([ 0.        ,  0.        ,  0.        , ...,  0.        ,
        0.        ,  1.43156374], dtype=float32),
       array([ 0.        ,  0.        ,  0.        , ...,  0.        ,
        0.62490147,  0.        ], dtype=float32),
       array([ 0.        ,  0.        ,  0.        , ...,  0.        ,
        8.82559299,  0.        ], dtype=float32),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.], dtype=float32),
       array([ 0.        ,  0.        ,  0.        , ...,  0.        ,
        4.05474567,  0.        ], dtype=float32),
       array([ 0.        ,  0.        ,  0.        , ...,  0.        ,
        6.83753395,  0.        ], dtype=float32),
       array([ 0.       ,  0.       ,  0.       , ...,  0.       ,  3.5112021,  0.       ], dtype=float32),
       array([ 0.        ,  0.        ,  0.        , ...,  0.        ,
        4.78147507,  0.        ], dtype=float32),
       array([  0.        ,   0.        ,   0.        , ...,   0.        ,
        12.43843079,   0

In [38]:
array_label = np.asarray(df['label_car2'])
array_label

array(['car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car',

In [40]:
array_label2 = df['label_car2'].values
array_label2

array(['car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car', 'car',
       'car', 'car',

In [51]:
svc = SVC()
logi = LogisticRegression()
features_cols = ['id','label_car']
logi.fit(df[features_cols].values, df['label_car2'].values)
#svc.fit(df['label_car'].values, df['label_car2'].values)
#predictions = svc.predict(df2['vgg16_features'])

ValueError: could not convert string to float: 'neg078.bmp'